/** @type {import('tailwindcss').Config} */
export default {
	content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
	theme: {
		extend: {
			colors: {
				ink: "rgb(var(--ink-rgb) / <alpha-value>)",
				void: "rgb(var(--void-rgb) / <alpha-value>)",
				paper: "rgb(var(--paper-rgb) / <alpha-value>)",
				pink: "rgb(var(--pink-rgb) / <alpha-value>)",
				cyan: "rgb(var(--cyan-rgb) / <alpha-value>)",
				yellow: "rgb(var(--yellow-rgb) / <alpha-value>)",
				lime: "rgb(var(--lime-rgb) / <alpha-value>)",
				violet: "rgb(var(--violet-rgb) / <alpha-value>)",
				red: "rgb(var(--red-rgb) / <alpha-value>)",
				bone: "rgb(var(--bone-rgb) / <alpha-value>)",
				muted: "rgb(var(--muted-rgb) / <alpha-value>)",
			},
			fontFamily: {
				sans: ["Space Grotesk", "ui-sans-serif", "system-ui", "sans-serif"],
				display: ["Bangers", "Impact", "Anton", "sans-serif"],
				pixel: ["'Press Start 2P'", "ui-monospace", "monospace"],
				mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
			},
			boxShadow: {
				hard: "6px 6px 0 var(--ink)",
				"hard-sm": "3px 3px 0 var(--ink)",
				"hard-pink": "6px 6px 0 var(--pink)",
				"hard-cyan": "6px 6px 0 var(--cyan)",
				"hard-yellow": "6px 6px 0 var(--yellow)",
				neon: "0 0 24px var(--pink), 0 0 48px color-mix(in srgb, var(--pink) 40%, transparent)",
			},
			typography: () => ({
				DEFAULT: {
					css: {
						"--tw-prose-body": "var(--ink)",
						"--tw-prose-headings": "var(--ink)",
						"--tw-prose-links": "var(--ink)",
						"--tw-prose-bold": "var(--ink)",
						"--tw-prose-quotes": "var(--ink)",
						"--tw-prose-quote-borders": "var(--pink)",
						"--tw-prose-code": "var(--ink)",
						"--tw-prose-pre-bg": "var(--void)",
						"--tw-prose-pre-code": "var(--bone)",
						"--tw-prose-hr": "var(--ink)",
						"--tw-prose-th-borders": "var(--ink)",
						"--tw-prose-td-borders": "var(--ink)",
						"--tw-prose-counters": "var(--pink)",
						"--tw-prose-bullets": "var(--pink)",
						maxWidth: "none",
						"h1, h2, h3, h4": { fontFamily: "Bangers, Impact, sans-serif", fontWeight: "400", letterSpacing: "0.02em" },
						h2: { fontSize: "2.4em" },
						h3: { fontSize: "1.8em" },
						a: { textDecoration: "none", background: "linear-gradient(transparent 55%, var(--yellow) 55%)", fontWeight: "600" },
						"a:hover": { background: "linear-gradient(transparent 0%, var(--yellow) 0%)" },
						blockquote: { fontStyle: "normal", background: "var(--bone)", padding: "1rem 1.25rem", borderLeftWidth: "6px" },
						code: { background: "var(--bone)", padding: "0.1em 0.35em", borderRadius: "0", fontWeight: "500" },
						"code::before": { content: "none" },
						"code::after": { content: "none" },
						pre: { border: "3px solid var(--ink)", borderRadius: "0", boxShadow: "6px 6px 0 var(--ink)" },
						img: { border: "3px solid var(--ink)", boxShadow: "6px 6px 0 var(--ink)" },
						hr: { borderTopWidth: "3px" },
					},
				},
			}),
		},
	},
	plugins: [require("@tailwindcss/typography")],
};
